In [72]:
import numpy as np
import pandas as pd

# step-1:Importing the data set

In [73]:
data=pd.read_csv("Diabities-210331-154610.csv")

In [74]:
data.head()

Unnamed: 0  Pregnancies  Glucose  blood pressure  skin thickness  Insulin  \
0         NaN          6.0    148.0            72.0            35.0      0.0   
1         NaN          1.0     85.0            66.0            29.0      0.0   
2         NaN          8.0    183.0            64.0             0.0      0.0   
3         NaN          1.0     89.0            66.0            23.0     94.0   
4         NaN          0.0    137.0            40.0            35.0    168.0   

    BMI  DiabetesPedigreeFunction   Age  Outcome  
0  33.6                     0.627  50.0      1.0  
1  26.6                     0.351  31.0      0.0  
2  23.3                     0.672  32.0      1.0  
3  28.1                     0.167  21.0      0.0  
4  43.1                     2.288  33.0      1.0

# step-2:analysing the data

In [75]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                0 non-null      float64
 1   Pregnancies               768 non-null    float64
 2   Glucose                   768 non-null    float64
 3   blood pressure            768 non-null    float64
 4   skin thickness            768 non-null    float64
 5   Insulin                   768 non-null    float64
 6   BMI                       768 non-null    float64
 7   DiabetesPedigreeFunction  768 non-null    float64
 8   Age                       768 non-null    float64
 9   Outcome                   768 non-null    float64
dtypes: float64(10)
memory usage: 60.2 KB


In [76]:
data.drop(data.tail(1).index,inplace=True)
data

Unnamed: 0  Pregnancies  Glucose  blood pressure  skin thickness  \
0           NaN          6.0    148.0            72.0            35.0   
1           NaN          1.0     85.0            66.0            29.0   
2           NaN          8.0    183.0            64.0             0.0   
3           NaN          1.0     89.0            66.0            23.0   
4           NaN          0.0    137.0            40.0            35.0   
..          ...          ...      ...             ...             ...   
763         NaN         10.0    101.0            76.0            48.0   
764         NaN          2.0    122.0            70.0            27.0   
765         NaN          5.0    121.0            72.0            23.0   
766         NaN          1.0    126.0            60.0             0.0   
767         NaN          1.0     93.0            70.0            31.0   

     Insulin   BMI  DiabetesPedigreeFunction   Age  Outcome  
0        0.0  33.6                     0.627  50.0      1.0  
1        0.0  26.6                     0.351  31.0      0.0  
2        0.0  23.3                     0.672  32.0      1.0  
3       94.0  28.1                     0.167  21.0      0.0  
4      168.0  43.1                     2.288  33.0      1.0  
..       ...   ...                       ...   ...      ...  
763    180.0  32.9                     0.171  63.0      0.0  
764      0.0  36.8                     0.340  27.0      0.0  
765    112.0  26.2                     0.245  30.0      0.0  
766      0.0  30.1                     0.349  47.0      1.0  
767      0.0  30.4                     0.315  23.0      0.0  

[768 rows x 10 columns]

In [77]:
x=data.iloc[:,1:-1]

x

Pregnancies  Glucose  blood pressure  skin thickness  Insulin   BMI  \
0            6.0    148.0            72.0            35.0      0.0  33.6   
1            1.0     85.0            66.0            29.0      0.0  26.6   
2            8.0    183.0            64.0             0.0      0.0  23.3   
3            1.0     89.0            66.0            23.0     94.0  28.1   
4            0.0    137.0            40.0            35.0    168.0  43.1   
..           ...      ...             ...             ...      ...   ...   
763         10.0    101.0            76.0            48.0    180.0  32.9   
764          2.0    122.0            70.0            27.0      0.0  36.8   
765          5.0    121.0            72.0            23.0    112.0  26.2   
766          1.0    126.0            60.0             0.0      0.0  30.1   
767          1.0     93.0            70.0            31.0      0.0  30.4   

     DiabetesPedigreeFunction   Age  
0                       0.627  50.0  
1                       0.351  31.0  
2                       0.672  32.0  
3                       0.167  21.0  
4                       2.288  33.0  
..                        ...   ...  
763                     0.171  63.0  
764                     0.340  27.0  
765                     0.245  30.0  
766                     0.349  47.0  
767                     0.315  23.0  

[768 rows x 8 columns]

In [78]:
y=data.iloc[:,-1]
y

0      1.0
1      0.0
2      1.0
3      0.0
4      1.0
      ... 
763    0.0
764    0.0
765    0.0
766    1.0
767    0.0
Name: Outcome, Length: 768, dtype: float64

# step-3:splitting the data set

In [79]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x, y, test_size=0.15, random_state=30)

# step-4:Train the model 

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
classifier1= LogisticRegression(solver='lbfgs',max_iter=1000)
classifier1.fit(X_train,y_train)


LogisticRegression(max_iter=1000)

In [81]:
from sklearn.naive_bayes import GaussianNB  
classifier2 = GaussianNB()  
classifier2.fit(X_train, y_train)  

GaussianNB()

# step-5:predict the result

In [83]:
y_pred1=classifier1.predict(X_test)
y_pred1
y_pred2=classifier2.predict(X_test)
y_pred2


array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.])

# step-6:lets check the accuracy score

In [86]:
accuracy=round(accuracy_score(y_pred1,y_test),2)*100
print(accuracy)
accuracy=round(accuracy_score(y_pred2,y_test),2)*100
print(accuracy)

80.0
78.0


In [87]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred1)  
print(cm)
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred2)  
print(cm)

[[70  7]
 [16 23]]
[[68  9]
 [16 23]]
